// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// L121
List L121(SEXP XX, SEXP YY, SEXP B0, SEXP Gm, SEXP mi, SEXP mg, SEXP mc);
RcppExport SEXP _PgaMsgl_L121(SEXP XXSEXP, SEXP YYSEXP, SEXP B0SEXP, SEXP GmSEXP, SEXP miSEXP, SEXP mgSEXP, SEXP mcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< SEXP >::type YY(YYSEXP);
    Rcpp::traits::input_parameter< SEXP >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< SEXP >::type Gm(GmSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mi(miSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mg(mgSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mc(mcSEXP);
    rcpp_result_gen = Rcpp::wrap(L121(XX, YY, B0, Gm, mi, mg, mc));
    return rcpp_result_gen;
END_RCPP
}
// L020v1
List L020v1(SEXP XX, SEXP YY, SEXP B0, SEXP Gm, SEXP mi, SEXP mg, SEXP mc);
RcppExport SEXP _PgaMsgl_L020v1(SEXP XXSEXP, SEXP YYSEXP, SEXP B0SEXP, SEXP GmSEXP, SEXP miSEXP, SEXP mgSEXP, SEXP mcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< SEXP >::type YY(YYSEXP);
    Rcpp::traits::input_parameter< SEXP >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< SEXP >::type Gm(GmSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mi(miSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mg(mgSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mc(mcSEXP);
    rcpp_result_gen = Rcpp::wrap(L020v1(XX, YY, B0, Gm, mi, mg, mc));
    return rcpp_result_gen;
END_RCPP
}
// L020v2
List L020v2(SEXP XX, SEXP YY, SEXP B0, SEXP Gm, SEXP mi, SEXP mg, SEXP mc, double minlambda, double rlambda, double mintau, double rtau);
RcppExport SEXP _PgaMsgl_L020v2(SEXP XXSEXP, SEXP YYSEXP, SEXP B0SEXP, SEXP GmSEXP, SEXP miSEXP, SEXP mgSEXP, SEXP mcSEXP, SEXP minlambdaSEXP, SEXP rlambdaSEXP, SEXP mintauSEXP, SEXP rtauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< SEXP >::type YY(YYSEXP);
    Rcpp::traits::input_parameter< SEXP >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< SEXP >::type Gm(GmSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mi(miSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mg(mgSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mc(mcSEXP);
    Rcpp::traits::input_parameter< double >::type minlambda(minlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type rlambda(rlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type mintau(mintauSEXP);
    Rcpp::traits::input_parameter< double >::type rtau(rtauSEXP);
    rcpp_result_gen = Rcpp::wrap(L020v2(XX, YY, B0, Gm, mi, mg, mc, minlambda, rlambda, mintau, rtau));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PgaMsgl_L121", (DL_FUNC) &_PgaMsgl_L121, 7},
    {"_PgaMsgl_L020v1", (DL_FUNC) &_PgaMsgl_L020v1, 7},
    {"_PgaMsgl_L020v2", (DL_FUNC) &_PgaMsgl_L020v2, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_PgaMsgl(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
