# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FPga_L121 <- function(XX, YY, B0, Gm, mi, mg, mc) {
    .Call('_PgaMsgl_FPga_L121', PACKAGE = 'PgaMsgl', XX, YY, B0, Gm, mi, mg, mc)
}

FPga_L020v1 <- function(XX, YY, B0, Gm, mi, mg, mc) {
    .Call('_PgaMsgl_FPga_L020v1', PACKAGE = 'PgaMsgl', XX, YY, B0, Gm, mi, mg, mc)
}

FPga_L020v2 <- function(XX, YY, B0, Gm, mi, mg, mc, minlambda = 1e-5, rlambda = 0.98, mintau = 1e-5, rtau = 0.98) {
    .Call('_PgaMsgl_FPga_L020v2', PACKAGE = 'PgaMsgl', XX, YY, B0, Gm, mi, mg, mc, minlambda, rlambda, mintau, rtau)
}

L121 <- function(XX, YY, B0, Gm, mi, mg, mc) {
    .Call('_PgaMsgl_L121', PACKAGE = 'PgaMsgl', XX, YY, B0, Gm, mi, mg, mc)
}

L020v1 <- function(XX, YY, B0, Gm, mi, mg, mc) {
    .Call('_PgaMsgl_L020v1', PACKAGE = 'PgaMsgl', XX, YY, B0, Gm, mi, mg, mc)
}

L020v2 <- function(XX, YY, B0, Gm, mi, mg, mc, minlambda = 1e-5, rlambda = 0.98, mintau = 1e-5, rtau = 0.98) {
    .Call('_PgaMsgl_L020v2', PACKAGE = 'PgaMsgl', XX, YY, B0, Gm, mi, mg, mc, minlambda, rlambda, mintau, rtau)
}

L121_test <- function(XX, YY, B0, Gm, mi, mg, mc, Beta, cutoff) {
    .Call('_PgaMsgl_L121_test', PACKAGE = 'PgaMsgl', XX, YY, B0, Gm, mi, mg, mc, Beta, cutoff)
}

L020v1_test <- function(XX, YY, B0, Gm, mi, mg, mc, Beta, cutoff) {
    .Call('_PgaMsgl_L020v1_test', PACKAGE = 'PgaMsgl', XX, YY, B0, Gm, mi, mg, mc, Beta, cutoff)
}

